# Numpy Lab
### (OSE July 2)

In [1]:
import numpy as np

### Problem 1

In [14]:
def solve_multiplication(A, B):
    return A @ B

In [15]:
A = np.array([ [3,-1,4], [1,5,-9] ])
B = np.array([ [2,6,-5,3], [5,-8,9,7], [9,-3,-2,-3]])
solve_multiplication(A, B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

### Problem 2

In [17]:
def Cayley_Hamilton(A):
    return -A@A@A + 9*A@A - 15*A

In [18]:
A = np.array([ [3,1,4], [1,5,9], [-5,3,1] ])
Cayley_Hamilton(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Problem 3

In [46]:
def calculate():
    A = np.triu(np.ones((7,7), dtype=np.int64))
    fives = np.triu(np.full((7,7), 5))
    minus_ones = np.tril(np.full((7,7), -1))
    print('A Matrix:', A)
    B = fives + minus_ones
    np.fill_diagonal(B, -1)
    print('B Matrix:', B)
    return A @ B @ A

In [47]:
calculate()

A Matrix: [[1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]]
B Matrix: [[-1  5  5  5  5  5  5]
 [-1 -1  5  5  5  5  5]
 [-1 -1 -1  5  5  5  5]
 [-1 -1 -1 -1  5  5  5]
 [-1 -1 -1 -1 -1  5  5]
 [-1 -1 -1 -1 -1 -1  5]
 [-1 -1 -1 -1 -1 -1 -1]]


array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

### Problem 4

In [52]:
def update_negatives(A):
    '''
    A: array
    '''
    B = np.copy(A)
    B[B<0]=0
    return B

In [53]:
A = np.array([1,2,3,4,-4,2,-8])
update_negatives(A)

array([1, 2, 3, 4, 0, 2, 0])

### Problem 5

In [76]:
def stack():
    A = np.arange(6).reshape((2,-1))
    print('A Matrix:', A)
    
    B = np.tril(np.full((3,3), 3))
    print('B Matrix:', B)
    
    C = np.diag([-2,-2,-2])
    print('C Matrix:', C)
    
    column_1 = np.vstack((np.zeros((3,3)),A,B))
    print('column_1', column_1)
    
    column_2 = np.vstack((A.T,np.zeros((3,2)),np.zeros((2,2))))
    print('column_2', column_2)
    
    column_3 = np.vstack((np.identity(3),np.zeros((2,3)),C))
    print('column_3', column_3)
    
    return np.column_stack((column_1, column_2, column_3))

stack()

A Matrix: [[0 1 2]
 [3 4 5]]
B Matrix: [[3 0 0]
 [3 3 0]
 [3 3 3]]
C Matrix: [[-2  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]
column_1 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 2.]
 [3. 4. 5.]
 [3. 0. 0.]
 [3. 3. 0.]
 [3. 3. 3.]]
column_2 [[0. 3.]
 [1. 4.]
 [2. 5.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
column_3 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [-2.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0. -2.]]


array([[ 0.,  0.,  0.,  0.,  3.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  4.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  2.,  5.,  0.,  0.,  1.],
       [ 0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  4.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

### Problem 6

In [91]:
def create_row_stochastic(A):
    '''
    A (2-D array): matrix
    '''
    column_sums = A.sum(axis=1).reshape(A.shape[0],-1)
    print("A Matrix:", A)
    return A / B

In [93]:
A = np.arange(9).reshape((3,3))
create_row_stochastic(A)

A Matrix: [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0.        , 0.33333333, 0.66666667],
       [0.25      , 0.33333333, 0.41666667],
       [0.28571429, 0.33333333, 0.38095238]])

### Problem 7

In [107]:
grid = np.load("grid.npy")
print(grid)

[[ 8  2 22 97 38 15  0 40  0 75  4  5  7 78 52 12 50 77 91  8]
 [49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48  4 56 62  0]
 [81 49 31 73 55 79 14 29 93 71 40 67 53 88 30  3 49 13 36 65]
 [52 70 95 23  4 60 11 42 69 24 68 56  1 32 56 71 37  2 36 91]
 [22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80]
 [24 47 32 60 99  3 45  2 44 75 33 53 78 36 84 20 35 17 12 50]
 [32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70]
 [67 26 20 68  2 62 12 20 95 63 94 39 63  8 40 91 66 49 94 21]
 [24 55 58  5 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72]
 [21 36 23  9 75  0 76 44 20 45 35 14  0 61 33 97 34 31 33 95]
 [78 17 53 28 22 75 31 67 15 94  3 80  4 62 16 14  9 53 56 92]
 [16 39  5 42 96 35 31 47 55 58 88 24  0 17 54 24 36 29 85 57]
 [86 56  0 48 35 71 89  7  5 44 44 37 44 60 21 58 51 54 17 58]
 [19 80 81 68  5 94 47 69 28 73 92 13 86 52 17 77  4 89 55 40]
 [ 4 52  8 83 97 35 99 16  7 97 57 32 16 26 26 79 33 27 98 66]
 [88 36 68 87 57 62 20 72  3 46 33 67 46 55 12 32 63 93

In [112]:
def greatest_right_diag(grid):
    return np.max(grid[:-3,:-3] * grid[1:-2, 1:-2] * grid[2:-1, 2:-1] * grid[3:, 3:])
greatest_right_diag(grid)

40304286

In [115]:
def greatest_vert(grid):
    return np.max(grid[:-3,:] * grid[1:-2, :] * grid[2:-1, :] * grid[3:,:])
greatest_vert(grid)

51267216

In [123]:
def greatest_left_diag(grid):
    return np.max(grid[3:,:-3] * grid[2:-1, 1:-2] * grid[1:-2, 2:-1] * grid[:-3, 3:])
greatest_left_diag(grid)

70600674

In [126]:
def greatest_adjacent_four(grid):
    return max(greatest_right_diag(grid), greatest_vert(grid), greatest_left_diag(grid))

In [127]:
greatest_adjacent_four(grid)

70600674